### ISSUE TITLE
This is not truly an issue but more of a question.

### ISSUE THREAD

**Issue by wsman217** [Morpheus1101/Avaritia#128]
Ok so I am using your code to learn how to mod. I have been going through and trying to understand how it all works and how it all comes together, but I found this little snippet, "ItemStack stack = getDataManager().get(ITEM);" in Avaritia/src/main/java/morph/avaritia/entity/EntityImmortalItem.java. This snippet contains a variable that comes from net.minecraft.entity.item.EntityItem; and it is a protected variable I am trying to understand how you managed to get the protected variable to actually work because whenever I try it it throws an error telling me that its not accessible.

**Comment by covers1624** [comment]
Hi!
Forge gives us what are called AccessTransformers, they allow us to change the access level of methods, fields and constructors in dev and at runtime. You can see Avaritia's AT file [here](https://github.com/Morpheus1101/Avaritia/blob/master/src/main/resources/avaritia_at.cfg). The lines used in AT's are in SRG mappings, If you are unfarmilliar with how Forge remaps minecraft ill give you a brief overview, Mojang ships the game in 'Notch' / Obf mappings, everything is completely obfuscated classes are named like `adb` and so on, methods and fields are similar, These names can change each time they release a new version of Minecraft, MCP is the underlying project that handles maintaining mappings from Obf to SRG. SRG mappings are _more_ human readable and is what mods are shipped in, classes have their final name `net.minecraft.client.blah.BlahClass` and methods are named in a index like fassion `func_123456_d` same for fields `field_1221232`, they are designed to be more of a common format for a group of versions, an example would be 1.12 and .1.12.2 they use the same SRG names for things (obviously different Obf names), MCP also keeps a set of mapping completely crowed sourced called MCP mappings, these are what you see in your dev environment and are meant to be human understandable. You can Contribute and lookup MCP names for things with MCPBot see [here](http://mcpbot.bspk.rs/) for more information. In order to use AccessTransformers with Forge you need a few more things, firstly is an access transformer file `your_at.cfg` stored inside your resources same as avaritia, add [this](https://github.com/Morpheus1101/Avaritia/blob/master/build.gradle#L93) line to your buildscript allong with [this](https://github.com/Morpheus1101/Avaritia/blob/master/build.gradle#L97-L99) and [this](https://github.com/Morpheus1101/Avaritia/blob/master/build.gradle#L103). If you have any more questions feel free to poke me on discord [here](https://discord.gg/9nr3qyC)
